name 'gene-packages'
maintainer 'David J Felix'
maintainer_email 'felix.davidj@gmail.com'
license 'MIT'
description 'Installs packages on a variety of systems'
long_description 'Installs packages through the standard package manager on a variety of systems'
version '0.1.0'
