name 'jetbrains'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jetbrains'
long_description 'Installs/Configures jetbrains'
version '0.1.0'
