name 'jetbrains-ide'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jetbrains'
long_description 'Installs/Configures jetbrains'
version '0.1.0'

depends 'adminuser', '~> 0.1.0'
depends 'gene-homebrew', '~> 0.1.0'
