name 'gene-bootstrap'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures gene-bootstrap'
long_description 'Installs/Configures gene-bootstrap'
version '0.1.0'
