name 'adminuser'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures adminuser'
long_description 'Installs/Configures adminuser'
version '0.1.0'
